image:
  name: "thg-ice/cluster-api-cleaner-openstack"
  tag: ""  # leave empty to default to chart's appVersion

registry:
  domain: ghcr.io

logLevel: 0

pod:
  user:
    id: 1000
  group:
    id: 1000
